version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...

  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/QuizApp-2-0.0.1-SNAPSHOT.jar
  discard-paths: yes
